disabled_rules: # rules to disable
  - trailing_whitespace
  - line_length

opt_in_rules: # rules to enable
  - empty_count

included: # paths to include (default: all)
  - RxAlamofire

excluded: # paths to exclude
  - Pods
  - Carthage
  - fastlane
  - build