# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1 

jobs:
  build:
    macos:
      xcode: "16.1" # Use your required Xcode version
    steps:
      # Step 1: Checkout code
      - checkout

      # Step 2: Restore cache for dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Podfile.lock" }}
      
      # Step 3: Install dependencies
      - run:
          name: Install CocoaPods
          command: |
            gem install cocoapods
            pod install

      # Step 4: Save cache for future builds
      - save_cache:
          paths:
            - Pods
          key: v1-dependencies-{{ checksum "Podfile.lock" }}

      # Step 5: Decode GoogleService-Info.plist (if applicable)
      - run:
          name: Decode GoogleService-Info.plist
          command: |
            echo $GOOGLE_PLIST_BASE64 | base64 --decode > GoogleService-Info.plist

      # Step 6: Build the iOS app
      - run:
          name: Build iOS App
          command: |
          xcodebuild -workspace RxAlamofire.xcworkspace \
                     -scheme RxAlamofire \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
                     clean build \
                     CODE_SIGN_STYLE=Automatic

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
