# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
 desc “Build, and push a release to AppCenter”
 
 lane :appcenter_release do
  build
  appcenter_upload(
   api_token: ENV['APPCENTER_KEY'],
   owner_name: ENV['APPCENTER_OWNER'],
   app_name: ENV['APPCENTER_APPNAME'],
   file: ENV['IPA_PATH'],
   notify_testers: true,
   destinations: ENV['APPCENTER_DESTINATION']
  )
  clean_build_artifacts
 end
 lane :build do
  gym(
  scheme: ENV['SCHEME'], 
  clean: true,
  export_method: ENV['IOS_EXPORT_METHOD'],
  output_directory: './builds',
  xcargs: "-allowProvisioningUpdates"
  )
 end
end