name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  run:
    runs-on: self-hosted
    name: Build iOS App

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Decode GoogleService-Info.plist (if applicable)
      - name: Decode GoogleService-Info.plist
        run: |
          base64 --decode -i encoded_plist.txt -o GoogleService-Info.plist
          
      # Step 3: Verify GoogleService-Info.plist
      - name: Verify GoogleService-Info.plist
        run: ls -a

      # Step 4: Build the iOS App for Simulator or Device
      - name: Build iOS App
        run: |
          xcodebuild -workspace RxAlamofire.xcworkspace \
                     -scheme RxAlamofire \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
                     clean build \
                     CODE_SIGN_STYLE=Automatic \
                     